### ISSUE TITLE
Breaking AmstelvarAlpha repo Away From Amstelvar Product repo: Now

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#101]
1. Google is preparing to give us the information required to go on with **AmstelvarRoman** and **AmstelvarItalic**. "_Amstelvar_" alone as a vf name will be reserved for a version that contains **both** Roman **and** Italic. 

A. The data for Roman and Italic can remain where it is currently reposited, and separate folders can be established for Roman and Italic masters, scripts and other data?, or 
B. the Roman Data can remain, the repo can be called "AmstelvarRoman" and a new repo can be made and called AmstelvarItalic?

Please chose one and let me know. 

2. We will be permanently moving away from all the AmstelvarAlpha masters in this new work, and doing the vast majority of design based on Newly redesigned Roman and Italic Defaults with an expanded glyph repertoire in the above mentioned repos, but...

AmstelvarAlpha is still being used and modified for purposes of the Font Bureau Variable fonts Brochure, and some amount of it may serve as model for AmstelvarRoman. It must have a separate repo now Called "AmstelvarAlpha". 

Keeping the two separate via Branch or anything but a separate repository is not useful to FB's process. Please let me know how quickly this can be complete. 

I then need to build a library of AmstelvarAlpha vfs with the versions of build scripts needed to demo all the needs of the brochure.  

Let me know questions, this week is critical.

Thanks.

**Comment by sannorozco** [comment]
1.
**Repo is set up with two folders**, Roman and Italic, as **Option A:** _The data for Roman and Italic can remain where it is currently reposited, and separate folders can be established for Roman and Italic masters, scripts and other data_

2.
**Amstelvar-Alpha repo created and everything Alpha related was moved there**, within sources folder, there’s a folder with the different versions with its corresponding masters and build scripts, this will work as a library of versions. As this, if needed another version, we can duplicate any folder and make the needed changes.
