### ISSUE TITLE
Amstelvar Crit III

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#102]
All understood and agreed to changes made. 
PDF uploaded here.
"CRIT"versions of Roman and Italic OPSZ min max and default on repository.

[Amtelvar opsz crit III.pdf](https://github.com/TypeNetwork/Amstelvar/files/2857707/Amtelvar.opsz.crit.III.pdf)

**Comment by davelab6** [comment]
Thanks!

With https://github.com/TypeNetwork/Amstelvar/commit/80c3735276baed8a46d0fc9b2b2fc6ce2091d585 containing 3,825 changed files in one commit, it's a pity I can't better review the steps taken, or even see quickly which files were updated.... Is there is a binary VF or 2 to look at, and a new PDF that shows the changes? :)

**Comment by davelab6** [comment]
Moved to another issue so closing. 

Thanks again DB!
