### ISSUE TITLE
Make Proofs of Amstelvar Crit III changes

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#103]
Repeat previous format client marked up. 

Previous marked-up proof enclosed.
[20190206082827560.pdf](https://github.com/TypeNetwork/Amstelvar/files/2865393/20190206082827560.pdf)

New versions in Repo with "CRIT" extension

**Comment by davelab6** [comment]
Thanks @dberlow :)

**Comment by pichotta** [comment]
@davelab6 

proof available in docs > 2019-02-15 crit III revisions
