### ISSUE TITLE
Adding Weights

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#105]
See Amstelvar Artboard 1 and let me know if you have questions. 
[Amstelvar Artboard.pdf](https://github.com/TypeNetwork/Amstelvar/files/2978750/Amstelvar.Artboard.pdf)
(Instructions are way up in the left-hand corner

Files are also uploaded into "Docs" folder.

**Comment by davelab6** [comment]
Any questions?
