### ISSUE TITLE
Weight controls for review

### ISSUE THREAD

**Issue by richardlipton** [TypeNetwork/Amstelvar#106]
Want to check in at the very start of these controls for the Thin and Black weight defaults.

I used the AstelvarAlpha’s wght-max for the Black (which I made a bit darker) and wght-min for the Thin
(which is unchanged) as a baseline start.

The Roman default shown in the middle (unchanged of course).

![Amstelvar controls](https://user-images.githubusercontent.com/10243945/55341766-35adcc00-5475-11e9-8bbe-10f65366e921.jpeg)

**Comment by dberlow** [comment]
Richard, 
The shapes and weights look great. 
I think for this size master the light is becoming slightly too condensed. 
And, i think the Bold is becoming too tightly spaces, and the serifs should lengthen with the addition of space.  
When correct, I think the width of the light should be around 90% of the default's width, while the black at this size master, needs to be wide enough to really read at this size. 

I went to set a smaller view but discovered the next issue posted.

**Comment by dberlow** [comment]
<img width="545" alt="Amstelvar-Roman-wghtmaxl c progress" src="https://user-images.githubusercontent.com/1956494/55471742-6bb79100-55d8-11e9-91f0-d86691f228c5.png">
