### ISSUE TITLE
Process correction requested

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#107]
Jill and Richard,

I specifically said that the work on this family was to proceed from the Default font data using the Amstelvar alpha data for reference only. 
That means:
Copy Amstelvar-Roman
Rename to Amstelvar-Black
Edit Font info, from: -Roman to -Black
Using Amstelvar Alpha as a guide, edit Roman to Black.

I went to check Richard's black controls at a size I could see and found my directions were not followed, that the data from the Alpha Black had been used to make the Amstelvar-Black.ufo controls and the font only contains the Alpha glyph repertoire. 

<img width="1919" alt="Screen Shot 2019-04-02 at 5 35 07 AM" src="https://user-images.githubusercontent.com/1956494/55392971-4f4d2300-550a-11e9-8056-31f2c73e410e.png">

This is a problem. Also, I see Light controls but nothing on the repo. This is also a problem. 

So stop. Let's talk. I'll tell you when to go again.

**Comment by richardlipton** [comment]
Sorry for the oversight, easy to fix.

**Comment by dberlow** [comment]
I have fixed it all. 

The folder with the Roman now contains complete controls for wght and wdth in the right files its the right names. 

A project has been created describing the next glyphs and styles to draw.

**Comment by richardlipton** [comment]
Geez David, I was busy workin' on this.....please don’t friggin do this to me again.
You told me something was wrong, so I began to make it right, let me do my job!

Curious to see how close my changes are to your fixes!

**Comment by richardlipton** [comment]
What is meant by a 'control point indice', the start point of the contour?

**Comment by dberlow** [comment]
Both what the starting point is and how many points there are in a contour

On Apr 2, 2019, at 11:11 AM, richardlipton <notifications@github.com> wrote:

What is meant by a 'control point indice', the start point of the contour?
