### ISSUE TITLE
Created Sheet for Values

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#111]
https://docs.google.com/spreadsheets/d/1JYewenc_Owd6L-ddOpr4KVwtCKOSoIds8ZbCaeICZN4/edit#gid=0

Please confirm invite.

**Comment by pichotta** [comment]
confirming invite to google spreadsheet with Amstelvar basic values.

**Comment by richardlipton** [comment]
confirming invite

**Comment by pichotta** [comment]
This is a New sheet fro Amstelvar containing three pages:
1. the values of the registered axes and measures for parametric axes in upm
2.the values of the registered axes and measures of parametric axes in 1/1000 for programming typography accurately.
3. the values of the registered axes and measures of parametric axes for successful production with the current tools. 

page 1 will be updated as the fonts change, rippling to page 2, to be used for programming in JS, but no int page 3, used for production of VF.

**Comment by sannorozco** [comment]
confirming
