### ISSUE TITLE
Corrupted font

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#119]
https://github.com/TypeNetwork/Amstelvar/tree/master/sources/Amstelvar-NewCharset/Roman/Amstelvar-Roman-XOPQmin.ufo

Was broken this morning after sync. It contains a complete ascii parametric extreme so I don't want to start over. 

I crashes RF with no message. 

A version from two days earlier:
https://github.com/TypeNetwork/Amstelvar/commit/c821e13a6775f15868c9c91a33dc755c59f65975#diff-005d22df9f54819eeb16789681e58b35

Should work, but restoring that version does not seem easy. 

Anyone know? look at the font and fix it, or replace it with the previous version. 

let me know. thanks.

**Comment by sannorozco** [comment]
I’ll look into it later today.

**Comment by dberlow** [comment]
Absolutely no problem, I’m shifting over to yogurt and then work on the brochure until Thursday. 

On Apr 30, 2019, at 5:11 PM, Santiago Orozco <notifications@github.com> wrote:

I’ll look into it later today.

**Comment by sannorozco** [comment]
Fixed in new update.
