### ISSUE TITLE
j acute

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#121]
<img width="1065" alt="Screen Shot 2019-05-06 at 1 29 04 PM" src="https://user-images.githubusercontent.com/1956494/57243012-03a70100-7003-11e9-8d34-f9d338d90c32.png">

Glyph Repertoire issue with j acute. 

Existing repertoire has had IJacute and ijacute added. 

If that's the case, fijacute and ffijacute must be added?

Also if that's the case Jacute or jacute should be added?

These glyphs have been added to Amstelvar-RomanDB.ufo, and are not in the other styles yet pending clarification to DB from Crossland and Pichotta so DB and SO can plan updates to Roman and Italic.

**Comment by pichotta** [comment]
include:
/Iacute_J.loclNLD 
/iacute_j.loclNLD 
/Jacute.loclNLD 
/jacute.loclNLD 

do not include:
/f_f_ijacute 
/f_ijacute 


IJ is only for Dutch. The addition of /fijacute is not necessary. 
The ij accents are rare, and following f even more rare and would not appear in a ligature.

**Comment by dberlow** [comment]
Is this being recommended or being done?

On May 24, 2019, at 9:36 AM, pichotta <notifications@github.com> wrote:

include:
/Iacute_J.loclNLD
/iacute_j.loclNLD
/Jacute.loclNLD
/jacute.loclNLD

do not include:
/f_f_ijacute
/f_ijacute

IJ is only for Dutch. The addition of /fijacute is not necessary.
The ij accents are rare, and following f even more rare and would not appear in a ligature.

**Comment by pichotta** [comment]
Both. If there is agreement then Richard can add these four glyphs to all masters.
/Iacute_J.loclNLD
/iacute_j.loclNLD
/Jacute.loclNLD
/jacute.loclNLD

**Comment by dberlow** [comment]
I agree

On May 24, 2019, at 10:07 AM, pichotta <notifications@github.com> wrote:

Both. If there is agreement then Richard can add these four glyphs to all masters.
/Iacute_J.loclNLD
/iacute_j.loclNLD
/Jacute.loclNLD
/jacute.loclNLD
