### ISSUE TITLE
Not seeing alll glyphs in Typetools

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#122]
Image attached is showing glphs in Robofont, left, and Typetyools, right. 

<img width="2418" alt="Screen Shot 2019-05-07 at 4 07 35 PM" src="https://user-images.githubusercontent.com/1956494/57329687-51df0180-70e2-11e9-95bb-92b6ff38e8a3.png">

SO, I'm pretty sure the glyphs that work are not cut off, and that the var contains all the glyphs in the ufo?

Chris, is there something in typetools that doesn't display all glyphs?

Let me know, thanks.

**Comment by sannorozco** [comment]
I’m seeing all glyphs marked in red at typetools, maybe clear cache??

<img width="1671" alt="Screen Shot 2019-05-07 at 4 17 23 PM" src="https://user-images.githubusercontent.com/1184152/57330414-f31a8780-70e3-11e9-9232-7c9afe09bbb8.png">

**Comment by dberlow** [comment]
Are you seeing the last 50 or so glyphs? ffij, e.g.?

**Comment by sannorozco** [comment]
Correction, I see only marked in red that has unicode, so NOT seeing ffij, fij, ijacute, and new combstack accents.

**Comment by chrissam42** [comment]
It currently only shows glyphs that are directly linked to a Unicode character via the cmap. I can add the ability to show OpenType-substitution alternates and ligatures. (Contextual alts are more complicated.) But there's no way I know of to show glyphs that aren't reachable from a souce Unicode string in HTML.
