### ISSUE TITLE
Six registered axes

### ISSUE THREAD

**Issue by richardlipton** [TypeNetwork/Amstelvar#123]
Char sets are completed, compatibilized and synched for:
Amstelvar-Roman-opsz-max
Amstelvar-Roman-opsz-min
Amstelvar-Roman-wdthmax
Amstelvar-Roman-wdthmin
Amstelvar-Roman-wghtmax
Amstelvar-Roman-wghtmin

**Comment by dberlow** [comment]
RL:Excellent! Take the rest of the day off;)
    Later you may proceed to complete glyph drawings for wght and wdth.
        no composites, just the glyphs and parts.

SO: can we get build with complete ascii today?

JP/CJ: can we get Ascii 3 axis QA weds late?

**Comment by sannorozco** [comment]
Yes, updated new VF build in repo.
