### ISSUE TITLE
Productizing: verify encoding

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#124]
double check that encoding exists for all glyphs in

**Roman-opsz-max**  
e.g.
		Ecircumflexgrave ['U+1EC0']
		ecircumflexhookabove ['U+1EC3']
		ecircumflextilde ['U+1EC5']
		ocircumflexdotbelow ['U+1ED9']

**Roman-opsz-min**
misc Uc, lc accents and /firstonechinese

**Comment by richardlipton** [comment]
Updated/fixed
