### ISSUE TITLE
Crossing Handle:  /J

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#125]
**Amstelvar-Roman-wghtmin**

re-draw/restructure /J tail while maintaining the shape

the current point structure is converting to a crossing bezier handle in the /J and related glyphs.  flag JP upon completion

J (49.0, -120.0)
	Jcircumflex (49.0, -120.0)
	IJ (779.0, -120.0)
	LJ (1263.0, -120.0)
	NJ (1649.0, -120.0)
	Lj (1263.0, -120.0)
	Nj (1649.0, -120.0)
	IJacute (779.0, -120.0)

![Screen Shot 2019-05-15 at 9 43 40 AM](https://user-images.githubusercontent.com/6576107/57780472-51ec8c00-76f6-11e9-8965-ab6f8652f2ba.png)

**Comment by richardlipton** [comment]
My outlines for this style’s glyph look different than your posted image:

![Roman-wghtmin J tail](https://user-images.githubusercontent.com/10243945/57789353-bfa0b400-7706-11e9-861f-f81ddbcae265.jpeg)

**Comment by pichotta** [comment]
yes, I am aware.  could you reposition these off-curves in /J for this style, while maintaining the shape, to see if it resolves the issue in the binary file?

**Comment by richardlipton** [comment]
J off-curves repositioned.
