### ISSUE TITLE
Outlines: /Ecircumflexhookabove

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#130]
widthmin is only master where the hook in /Ecircumflexhookabove does not visually 
connect, which may lead to less than optimal placement across the range of the space.

![:Ecircumflexhookabove](https://user-images.githubusercontent.com/6576107/58177555-99cd5f00-7c72-11e9-95e7-802c586b30c4.png)

![wdthmin Ecircumflexhookabove](https://user-images.githubusercontent.com/6576107/58184579-5f1df380-7c7f-11e9-9962-25fe3b984722.png)

**Comment by dberlow** [comment]
Thanks,
What's the rest of the address in the design space of the image shown?
opsz, etc..
Image doesn't look like width min, also
if a contour point of the hook 'wants' to anchor on a contour point of the
E, is that possible?

**Comment by sannorozco** [comment]
There are two intermediates that need to be regenreted to fix these shifts. When we adjusted the designspace from default to opszmax .

https://github.com/TypeNetwork/Amstelvar/issues/117

**Comment by richardlipton** [comment]
width-min /Ecircumflexhookabove fixed.
