### ISSUE TITLE
Kerning question: /periodcentered.loclCAT /periodcentered.loclCAT.case 

### ISSUE THREAD

**Issue by xxdgwxx** [TypeNetwork/Amstelvar#134]
How should these be handled? For MWA, these characters were spaced so that they would replicate the Ldotaccent and ldotaccent, without any kerning. These are spaced wider, is it preferable that they be kerned to replicate Ldotaccent/ldotaccent? Or respaced as in MWA?

**Comment by dberlow** [comment]
Follow MWA.
