### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Amstelvar#135]
I'd like to see this project building the binaries using Travis Continuous Integration, and posting them to the `gh-pages` branch.

Happy to provide more details/context if this doesn't make sense.

**Comment by davelab6** [comment]
It's been a month with no update on this issue :) what's occuring? 

To avoid stacking GF Early Access further, I'd like to use GitHub Pages for serving bulletproof CSS and eot/woff/woff2  made via the source build script process for the builds coming out of Travis.

**Comment by michelleperham** [comment]
Sorry there has been no update. We've been testing this and will coordinate the designers to get it implemented.

**Comment by cjdunn** [comment]
@davelab6 Travis CI has now been implemented. 

Anytime a commit for Amstelvar is pushed to github, Travis will run the build script and test if the repo is building. If a build is successful on the `master` branch, Travis will push the updates to the `gh-pages` branch of the Amstelvar repo. I’ve added a basic html proof which will use the latest fonts from the `gh-pages` branch, and you can see the proof via this URL:
https://typenetwork.github.io/Amstelvar/proof/

Please let us know if this satisfies your requirements, thanks!
