### ISSUE TITLE
Duovars at opsz

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#138]
Santiago,

I'm catching up on the documentation of this project. 
In the sketch file, Docs/Amstelvar Designspace Map 3,
"Roman Plaques" seen here in pink
<img width="1128" alt="Screen Shot 2019-06-02 at 1 46 33 PM" src="https://user-images.githubusercontent.com/1956494/58765101-14349380-853d-11e9-8fb0-adfd856eebd9.png">

This picture, and Designspace file show
Amstelvar-Roman-opsz-max-wgthmin
Amstelvar-Roman-opsz-max-wgthmax
unfinished and effecting the whole opsz max design space.

What are these instances for?

Let me know thanks.

**Comment by sannorozco** [comment]
Let me check the history, I’ll get back at you later today.

**Comment by sannorozco** [comment]
Hey,
I believe they’ve been there since the beginning, and only ascii have been updated.
I’ve looked in the first version of the design space defined in the docs:

Docs/AMSTELVAR DESIGNSPACE MAP1b.pdf 

I remember the Controls and ascii were updated to correct them, we can see the difference between _“designspace map1” page 2_,  and the most recent _“designspacemap3” page 3_.

**Comment by dberlow** [comment]
If I open the design space file 4, Save it has 5, mute those two styles
 then every glyph is working.

 I do not think they’ve been there “since the beginning”, as all Docs/AMSTELVAR DESIGNSPACE MAP1b.pdf shows is those styles are marked “trouble” but that was two versions of that file and a month ago. 

I can’t find anything in that document it says generate these two instances and then leave them in the space incomplete. Is there a history of the design space file before and after where those were added, thanks.



On Jun 2, 2019, at 6:09 PM, Santiago Orozco <notifications@github.com> wrote:

Hey,
I believe they’ve been there since the beginning, and only ascii have been updated.
I’ve looked in the first version of the design space defined in the docs:

Docs/AMSTELVAR DESIGNSPACE MAP1b.pdf

I remember the Controls and ascii were updated to correct them, we can see the difference between “designspace map1” page 2, and the most recent “designspacemap3” page 3.
