### ISSUE TITLE
VF Build issues

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#141]
SO, 
**can you make sure the detail instructions for the YOPQ correction and the interpolation of the 84 pt and 36 pt masters are available to CJ?**

They are both referenced below. 

CJ, 

Pictured is OPSZ MAX, WGHT MIN. 
<img width="1187" alt="Screen Shot 2019-06-03 at 6 55 35 PM" src="https://user-images.githubusercontent.com/1956494/58839847-7cfd3800-8631-11e9-954e-b7032a70ae8b.png">

As Explained and documented previously:

2. OPSZ MAX, WGHT MIN has a delta overload that makes the hairlines, YOPQ, become negative. 
After OPSZ WGHT MIN can be made current,  use YOPQ to correct OPSZ MAX, WGHT MIN’s hairline. 

**Then add that instance to the build as OPSZ MAX WGHT MIN!**

**Detailed instructions fo the values are on the repo.** (note: this will eventually repeat in the italic opsz!)

Here are the complete instructions again with the above repeated. 

There is also a generation of the OPSZ masters for 84 and 36. Did that get followed?

SO has the **values** for that as well. 

**Where do we want to store such things?**

B. Instructions for building Amstelvar (Roman) INTERNAL prototype.

1. OPSZ - uses 5 masters for the build:
  1. Default (14)
  2. opsz min (8)
  3. opsz max (144)
  4. opsz 36
  5. opsz 84

Note: We are not manipulating 36 or 84 point, they are created immediately before variation production to catch any changes to the default or opsz max, interpolated to redistribute the variation of optical size over the range from 14 to 144 as a rough curve. The values along opsz for 36 and 84 are on the repo, along with other documentation of this issue. 

2. OPSZ MAX, WGHT MIN has a delta overload that makes the hairlines, YOPQ, become negative. 
After OPSZ WGHT MIN can be made current, use YOPQ to correct OPSZ MAX, WGHT MIN’s hairline. 
Detailed instructions fo the values are on the repo. 

**Then add that instance to the build at OPSZ MAX WGHT MIN!!**

(note: this will eventually repeat in the italic opsz!)

3. WGHT and WDTH have max and min masters, and are straight-forward. 

4. whatever else is standard for generating a variable font of this kind, please do and document the steps. 

5. Proof the internal prototype in typetools, “glyphs” format, see docs/AMSTELVAR DESIGNSPACE MAP 3.sketch. Last two big pages, one is for Roman,. grab the screens and increment the sketch file name, update the sketch doc.

6. When all ascii is working, not that it’s all perfect, just that it works, deliver to me. 

7. I will proof and fix glyphs.

8. I will recommend tailoring of axes to improve result.

**Comment by sannorozco** [comment]
Yes, here they are @cjdunn 

**For generate the instances at opsz36 and opsz84**

—Make sure you remove them from the latest designspace
—Generate instance opsz 137 and assign it in the designspace intermediate at opsz 84
—Generate instance opsz 78 and  assign it in the designspace intermediate at opsz 36
—So we catch any update in opsz
—You can see how we’ve done it and the reasoning behind in this issue https://github.com/TypeNetwork/Amstelvar/issues/117

-----

**YOPQ correction**

—Then with this new designspace locate at opszmax wghtmin
—Use YOPQ to adjust the reversed hairlines 
—Finally generate this corrected duovar and add it to the designspace (right @dberlow??)

Let me know,

**Comment by dberlow** [comment]
Yes, but what’s the value for the YOPQ correction?

Thanks.

On Jun 3, 2019, at 7:29 PM, Santiago Orozco <notifications@github.com> wrote:

Yes, here they are @cjdunn

For generate the instances at opsz36 and opsz84

—Make sure you remove them from the latest designspace
—Generate instance opsz 137 and assign it in the designspace intermediate at opsz 84
—Generate instance opsz 78 and assign it in the designspace intermediate at opsz 36
—So we catch any update in opsz
—You can see how we’ve done it and the reasoning behind in this issue #117

YOPQ correction

—Then with this new designspace locate at opszmax wghtmin
—Use YOPQ to adjust the reversed hairlines
—Finally generate this corrected duovar and add it to the designspace (right @dberlow??)

Let me know,

**Comment by sannorozco** [comment]
Updated
