### ISSUE TITLE
116 Suffix?

### ISSUE THREAD

**Issue by magdairis** [TypeNetwork/Amstelvar#149]
What does the 116 suffix in font file names mean, e.g. what's the difference between Amstelvar-Roman-VF116.ttf and Amstelvar-Roman-VF.ttf?

**Comment by dberlow** [comment]
Good question, thanks. I do not believe there is a difference. 

This is likely now a relic of the pre-Travis days we just ended, when we were trying to keep versions of the build files and fonts by our on integration customs.

The numbered version eventually went into the history, and the un-numbered version allowed us to have other code based on a consistent font file name.

 Jul 4, 2019, at 2:53 AM, Magda Iris Petford <notifications@github.com> wrote:

What does the 116 suffix in font file names mean, e.g. what's the difference between Amstelvar-Roman-VF116.ttf and Amstelvar-Roman-VF.ttf?

**Comment by sannorozco** [comment]
Only the latest versions are in fonts/ now, and added readme descriptions.
