### ISSUE TITLE
Amstelvar Roman: For Vietnamese edits

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#154]
Changed shapes of:
Stacking acute and grave
U&lc hornf, U and u hornu, 

Widths of:
all horned glyphs and accented horned glyphs. 

Compositions of:
All stacked-above glyphs U & l.c.
All horned glyphs U & l.c.

**Comment by davelab6** [comment]
@sannorozco says DB has made the components for the vietnamese horns, so closing
