### ISSUE TITLE
STAT table, axis order

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/Amstelvar#16]
I have committed a first draft of a stat table 5a067fc4e3fffe66740205055a9c3f20306ae850.

@dberlow do you have a preferred order in which the axes should be displayed?

**Comment by dberlow** [comment]
Cool. Optical size, weight, width, contrast, paraweight, parawidth, serif rise, xht. And whatever I left off last.

**Comment by djrrb** [comment]
Order updated (Grade is last) and a preliminary STAT table is inserted into Variations TTF. 7f77e36f3cef0eaad7e068e6454ed6cb91111955

I'm leaving this issue open until I coordinate with @asaumierdemers on how to incorporate this into future builds.

**Comment by dberlow** [comment]
You're too quick, is this slider order the only thing in there?

If not please list.

If there are parametric values for each axis? we want them in 1/1000 of an
em (in Direct Competition to OS/2 values.) as far as I know this means you
can 1/2 the current values from the 2000 ppm of Amstelvar.

What else is in there?

**Comment by davelab6** [comment]
Is the stat table and order now set up in the build process?

**Comment by davelab6** [comment]
Is the stat table and order now set up in the build process?

**Comment by djrrb** [comment]
Not as far as I know. Ideally we would use the tools mentioned in this comment: https://github.com/TypeNetwork/fb-Decovar/issues/3#issuecomment-311130047

**Comment by sberlow** [comment]
@djrrb is the stat table and order in the build script?

**Comment by djrrb** [comment]
The STAT table is definitely in there. 

Will review order in upcoming build and close if this seems consistent with the list up top.

**Comment by davelab6** [comment]
Do you mean in https://github.com/TypeNetwork/Amstelvar/blob/552fadbbb0a6a6405da8fadb4156a269abe94e38/sources/Amstelvar-Roman.designspace ?

That has these axes in this order

* Optical Size
* x opaque
* x transparent
* y opaque
* y transparent lowercase
* y transparent uppercase
* y transparent figure height
* y transparent lowercase descender
* y transparent lowercase ascender
* serif rise

For those items, this is good for me. However, I would expect as more axes are added that their order will be something like:

* Optical Size
* Weight
* Width
* Grade
* x opaque
* x transparent
* y opaque
* y transparent lowercase
* y transparent uppercase
* y transparent figure height
* y transparent lowercase descender
* y transparent lowercase ascender
* serif rise

**Comment by davelab6** [comment]
https://github.com/daltonmaag/statmake/issues/7 may be relevant to this

Also #14

**Comment by madig** [comment]
(statmake is a small utility that takes an almost-verbatim STAT table definition and applies it to a VF, the difference being that it is somewhat easier to write/maintain than a TTX dump.)

**Comment by davelab6** [comment]
Closing as related to Amstelvar Alpha
