### ISSUE TITLE
opsz issue with os and apps

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#160]
The issue is that software doesn’t know what to do with sizes outside of opsz.
https://mobile.twitter.com/Typelady/status/1150489276750209024

I don’t think apple can fix it.

But we can fix this without really changing any of our data.
I’d like a build of the design space that duplicates 0PSZ min, (8), and while leaving the current opszmin at 8, And add the same master to the designspace at OPSZ 1.
and while leaving opsz max at 144, copy and add it again to a new opsz1000.

The opsz then, will have instances at 1,8,14,36,84,144 and 1000. 8-144 will remain identical, < 8 will show 8, from 1-8, >144 will show 144, from 144-1000. 

That’s what apps are supposed to do but we can make them do it by putting it in the font.

Let me know.

**Comment by sannorozco** [comment]
Yeah, that seems an implementation error at OS level, that will take soooome time to fix it.

—Added Amstelvar-Roman-APPS.ttf
—With its Amstelvar-Roman-008-APPS.designspace
—opsz intermediates at 1,8,14,36,84,144, & 1000
—extended designspace 1=8 & 144=1000

Le me know if you want it on a specific folder and name, also, for how long this should be on the repo.

**Comment by dberlow** [comment]
Dave, and the developer claim it’s fixed from 10.16 on.;(

But if you make it anyway, it’s a good lesson for all apps, and 10.16,is not out until “fall”

Please test to make sure it works.

Let me know if that sounds right to do to you too. If so, why not just keep this in the main branch?

On Jul 23, 2019, at 4:18 PM, Santiago Orozco <notifications@github.com> wrote:

Yeah, that seems an implementation error at OS level, that will take soooome time to fix it.

—Added Amstelvar-Roman-APPS.ttf
—With its Amstelvar-Roman-008-APPS.designspace
—opsz intermediates at 1,8,14,36,84,144, & 1000
—extended designspace 1=8 & 144=1000

Le me know if you want it on a specific folder and name, also, for how long this should be on the repo.
