### ISSUE TITLE
Italic YOPQ

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#161]
This looks like good work, I've looked at Italic and the yopq mins and max of U&lc, the real review is after vf is made. So let's do that soon. 

Some observations. 
The angle at the end of the terminal should remain the same in all. Max seems off.
<img width="377" alt="Screen Shot 2019-08-07 at 9 36 36 AM" src="https://user-images.githubusercontent.com/1956494/62627455-71f7aa00-b8f7-11e9-9407-ee632058bf77.png">

There is a change of XOPQ, bottom left of "h", where YOPQ min is loosing weight in all these kind of lc. stems.
<img width="565" alt="Screen Shot 2019-08-07 at 9 36 46 AM" src="https://user-images.githubusercontent.com/1956494/62627536-905da580-b8f7-11e9-8fbd-074d47edec97.png">

There is a change of angle in the z top serif of YOPQ min, perhaps others, that needs to remain the same as default and max or it gets hairy later. 

<img width="732" alt="Screen Shot 2019-08-07 at 9 38 10 AM" src="https://user-images.githubusercontent.com/1956494/62627804-11b53800-b8f8-11e9-925f-2fb90e8ac239.png">

**Comment by dberlow** [comment]
Richard, 
where are the Roman issues on YOPQ marked?
thanks.

**Comment by sannorozco** [comment]
Updated Italic VF with YOPQ axis from RL.

**Comment by richardlipton** [comment]
The Roman issues on YOPQ max are marked in red and on the repo. They are just general flags as to whether the glyph had been modified for the axis or not.

**Comment by dberlow** [comment]
... on the repo, in the source folder, in the ufo, I got now:)

On Aug 8, 2019, at 8:22 AM, richardlipton <notifications@github.com> wrote:

The Roman issues on YOPQ max are marked in red and on the repo

**Comment by richardlipton** [comment]
The terminal angle issues in the YOPQ have been addressed.

**Comment by sannorozco** [comment]
And in the Amstelvar-Italic-VF.
