### ISSUE TITLE
Default italic spacing 

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#164]
I’ve seen this happen before in much earlier builds of Roman:
Current build has an error In storing the widths of the default italic?
![73891715-C65E-44A0-BCBD-4327116A6A66](https://user-images.githubusercontent.com/1956494/63216795-d93c0800-c108-11e9-8b20-2d497549fae0.png)
...and much of the opsz max spacing is not correct, possibly as a result. 
![AD2F83D1-8A6D-4E13-81C2-B54CCDDCF809](https://user-images.githubusercontent.com/1956494/63216800-eeb13200-c108-11e9-9b22-f19ff0e87c5f.png)

**Comment by sannorozco** [comment]
This is fixed now, I updated the requirements on my end for other projects, now rolled back for this specific repo.
