### ISSUE TITLE
Accents checked

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#165]
There are some issues with yopq of accents at lightest wts, I will check out.

Y with dot above is migrating to being below on opsz. 
  See video proof 
From: Amstelvar Roman: Array: opsz 14 wdth 125 wght 402
To: Amstelvar Roman: Array: opsz 144 wdth 100 wght 400

Otherwise looks great

**Comment by sannorozco** [comment]
This is fixed now.
