### ISSUE TITLE
Spacing issues in italic default

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#166]
Not saying this is  masters, but it is messing up the lowercase spacing in the entire design space, making review impractical at this time.

[1915218E-9283-472F-A73A-798F221ADE16](https://user-images.githubusercontent.com/1956494/62962094-29932d00-bdcc-11e9-8c05-05597abf85d3.png)
![71D28363-BBBD-40C4-AB34-69E3C2BCD22A](https://user-images.githubusercontent.com/1956494/62962095-29932d00-bdcc-11e9-805a-906d2c047742.png)

**Comment by sannorozco** [comment]
This is fixed now, it was a font issue.

<img width="1868" alt="Screen Shot 2019-08-21 at 11 37 31 AM" src="https://user-images.githubusercontent.com/1184152/63450683-24576300-c408-11e9-81bc-efb918817b9c.png">
