### ISSUE TITLE
Amstelvar widths issue

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#167]
Opsz 14, wghtmin, wdthmin metrics not correctly producing in var.
<img width="1441" alt="Amstelvar Bug Bold Spacing" src="https://user-images.githubusercontent.com/1956494/66124985-d2cbf780-e5b3-11e9-8763-5ca46b8413c1.png">

Masters and skateboard preview left. Variable font showing same instance at right in typetools. Spacing confirmed in illustrator.

**Comment by cjdunn** [comment]
@dberlow If you look at the var font built by Travis CI, do you still see the problem? 
https://github.com/TypeNetwork/Amstelvar/blob/gh-pages/fonts/Amstelvar-Roman-VF.ttf

(attached here for reference) 
[Amstelvar-Roman-VF.ttf.zip](https://github.com/TypeNetwork/Amstelvar/files/3687055/Amstelvar-Roman-VF.ttf.zip)

**Comment by dberlow** [comment]
Thanks CJ.
Was anything special needed, or just the same designspace file and masters
corrected the issue?

The old Amstelvar is now in the old folder, this version is in the fonts
folder.
