### ISSUE TITLE
Greek uppercase

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#176]
<img width="321" alt="Screen Shot 2020-06-16 at 7 09 26 AM" src="https://user-images.githubusercontent.com/1956494/84774591-0c128f00-afac-11ea-8151-0f4ae4083a9a.png">

I’m looking at this and very happy to see it.

A couple of general comments on specific glyphs.
1. Delta should have the same bisected diagonals as Alpha and Lambda. If existing delta was wrong please excuse. In general most lines in the font are not straight throughout the design space, with exception of those on baseline.
2. Gamma width is narrower than L and F. This might look right now, but please be sure to consider It as the ramifications of width and opsz ranges are designed.
3. Xi is looking a bit light at 14? 

I look forward to seeing more and can put examples in the background of this UFO if you wish. Cheers!
dberlow

**Comment by irenevl** [comment]
Hi @dberlow 

Sorry for the delayed answer. I was attending the Grapholinguistics conference virtually in Paris. Thank you for the feedback. Just a note, the uppercase that is in the centre master, it is incomplete and very much a first draft.

My completed glyphs at this point are the key glyphs `ηρεμια` for the centre master, and first drafts for the 8 corner masters to make sure I am on the right track.

> [1] Delta should have the same bisected diagonals as Alpha and Lambda. If existing delta was wrong please excuse. In general most lines in the font are not straight throughout the design space, with exception of those on baseline.

That was my first approach, but without the middle bar of the A, and with the horizontal bottom stroke, the counter ends up with a really weird shape. I do prefer to keep this shape consistent with Alpha and Lambda so I will have another go.

> [2] Gamma width is narrower than L and F. This might look right now, but please be sure to consider It as the ramifications of width and opsz ranges are designed.

I believe it’s a standard approach to have the Gamma 10-20 units narrower than F and L. If it’s on the same width as F and L, it creates a massive gap with combinations with lowercase, that of course can be dealt with in kerning. But when these combinations come with diacritics, these accented glyphs clash on the top with Gamma’s horizontal stroke and these kerning groups that were fixing the problem before now they need to break up and exceptions need to be added. I will be consistent across the rest of the styles, except I may use the Regular width masters as the lower boundaries for this behaviour. I’ll keep notes on these decisions.

> [3] Xi is looking a bit light at 14?

Yup. I’ll update it.

Thanks for suggesting drawing for me, this time I think it’s fine. By Friday I will have the first full set of the central master and proofs.

**Comment by dberlow** [comment]
Thanks for the feedback feedback.
Looking forward to Gamma's adventures in design space, and yes, kerning, is
not going to take care of everything.
But, I'm hesitant to make such a glyph compromise it's primary function,
which, as a member of the uppercase, is uppercase, for rare lowercase
adjacencies.
I'm wondering if a narrow, for use before l.c.-accented-glpyh Gamma should
just be included, at least in Amstelvar. Have you ever seen one?

**Comment by irenevl** [comment]
Usually the Gamma and I think also the Cyrillic Ge are a touch narrower than F and L. Most typefaces, as far as I know, have only one form and they either kern positive with the clashing accented lc or pretend that these pairs never exist :)

**Comment by sannorozco** [comment]
Hallo @irenevl! we’re wondering this is implemented in the masters?

**Comment by davelab6** [comment]
If yes, please close
