### ISSUE TITLE
Greek in VF build 20200707

### ISSUE THREAD

**Issue by irenevl** [TypeNetwork/Amstelvar#179]
Hi @sannorozco 
in the latest VF build 2890073d772ff2d9b5f2e39e03219999ed2743d0

I've noticed that were some glyphs that didn’t interpolate at all. AFAIK there were no missing glyphs from the sources or had any compatibility problem. Did you get any errors?
The characters are:
alpha, epsilon, eta, theta, iota and mu.
![Amstelvar-Roman wdth,wght,opsz](https://user-images.githubusercontent.com/11784297/87300231-2e012200-c516-11ea-9461-2b932cdd7b7d.gif)

**Comment by sannorozco** [comment]
Hallo @irenevl!

These incompatibilities might be in all other masters you’re not currently working on, maybe check on those?

Here’s the report:

INFO:fontTools.varLib:Generating gvar
WARNING:fontTools.varLib:glyph Gamma has incompatible masters; skipping
WARNING:fontTools.varLib:glyph alpha has incompatible masters; skipping
WARNING:fontTools.varLib:glyph epsilon has incompatible masters; skipping
WARNING:fontTools.varLib:glyph eta has incompatible masters; skipping
WARNING:fontTools.varLib:glyph theta has incompatible masters; skipping
WARNING:fontTools.varLib:glyph iota has incompatible masters; skipping
WARNING:fontTools.varLib:glyph mu has incompatible masters; skipping
WARNING:fontTools.varLib:glyph omegatonos has incompatible masters; skipping

**Comment by irenevl** [comment]
Hi!
it shouldn't have any incompatibilities since the other masters don't include anything new, just copy of the Romans.
BTW I have new MIN and MAX wght and at the end of today MIN and MAX opsz, if you want to make a new build :)

**Comment by dberlow** [comment]
Very cool, thanks!

On Jul 14, 2020, at 2:13 AM, Irene Vlachou <notifications@github.com> wrote:

﻿
Hi!
it shouldn't have any incompatibilities since the other masters don't include anything new, just copy of the Romans.
BTW I have new MIN and MAX wght and at the end of today MIN and MAX opsz, if you want to make a new build!
