### ISSUE TITLE
Italic commaaccentcomb.case

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#180]
Contour is wrong direction in all masters except:
Default
Amstelvar-Italic-opsz144-wght900-wdth100

**Comment by sannorozco** [comment]
Fixed this and some more wrong directions.

**Comment by dberlow** [comment]
More!?Arrrrgggggg@#$5^

On Jul 30, 2020, at 12:39 PM, Santiago Orozco <notifications@github.com> wrote:

﻿
Fixed this and some more wrong directions.

**Comment by sannorozco** [comment]
just one more, two un total.
