### ISSUE TITLE
Amstelvar Greek l.c.

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#181]
Pictured l.c. glyphs not varying in opsz or opsz 14, wdth or wght?
![29B633E4-DBD2-4B5D-9572-79BC58138052](https://user-images.githubusercontent.com/1956494/88684528-fb812880-d0c2-11ea-846f-f0ad620c10a7.png)
![A3AACFB9-EB30-4824-93EC-0192D5356E93](https://user-images.githubusercontent.com/1956494/88684531-fcb25580-d0c2-11ea-9d4d-b1b2a8893852.png)

**Comment by sannorozco** [comment]
Yes, Irene is working on compatibilizing those lc glyphs, as soon as they’re in repo I’ll update the build.

**Comment by irenevl** [comment]
Just uploaded the updated files:
20200728 Greek WIP commit:
update corner masters' control characters (α ε η ι ο ρ )compatibility

**Comment by sannorozco** [comment]
Updated VF with Irene’s fixes, looks good now, thank you Irene!
