### ISSUE TITLE
14 900 125 Greek l.c. edits

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#184]
Greek l.c. edits, 14 900 125
These are extrapolations, so i’d not expect ideal results over the style range.

14 900 125
is the 50-50 child of
14 900 100
14 400 125 &
14 400 100 is the default.

the 14 900 125 ufo has originals in background, 
Edits in foreground.

Glyphs marked as follows:
red=shape edits, most related to maintaining angles of terminals and serifs at alignment zones.
yellow= changed as composites, via source and accent edits, width and accent positioning also change. 
green= sigma is probably troubled in 14 900 100 and/or 14 400 125?
blue = made side bearing =, matching latin l.c. o.

**Comment by irenevl** [comment]
Thanks David,

thanks for the 14 900 125 and your notes. Here is what I found and updated.

Green:

Lower case sigma: you are right, I had to updated both the 14 400 125 and 14 900 100

Red:

beta: the junction looks too thin I think, so I checked the 14 900 100, and made it heavier by 50% and a tiny bit heavier in the 14 400 125. Please extrapolate again the beta.

delta: looked too narrow so I updated the 14 900 100 and 14 400 125. Please extrapolate delta again.

xi and zeta: both seemed narrow in 14 900 125 so I updated the 14 900 100 and 14 400 125. Please extrapolate again both zeta and xi.

tau: also looked too narrow so I updated the 14 900 100 and 14 400 125. Please extrapolate again both tau.

upsilon and psi: the contrast looked a bit weird in the extrapolated 14 900 100, so I reworked in both 14 900 100 and 14 400 125. Please extrapolate again both.

omega: it looked a bit thin, especially on the base so I updated the 14 900 100. Please extrapolate again omega.

Yellow:

**Comment by dberlow** [comment]
Thanks so much for this. 
I am finishing 14 900 50, similarly, tonight,
14 100 50 and 14 100 125 will be done tomorrow and gathering all in time for end of week.
So I’m hoping to get your comments like this and the minor fixes on the sources to the 4 you did by the end of Friday and then I’ll do a re-extrapolation and synthesize in your additional changes.

On Aug 12, 2020, at 3:10 PM, Irene Vlachou <notifications@github.com> wrote:

﻿
Thanks David,

thanks for the 14 900 125 and your notes. Here is what I found and updated.

Green:

Lower case sigma: you are right, I had to updated both the 14 400 125 and 14 900 100

Red:

beta: the junction looks too thin I think, so I checked the 14 900 100, and made it heavier by 50% and a tiny bit heavier in the 14 400 125. Please extrapolate again the beta.

delta: looked too narrow so I updated the 14 900 100 and 14 400 125. Please extrapolate delta again.

xi and zeta: both seemed narrow in 14 900 125 so I updated the 14 900 100 and 14 400 125. Please extrapolate again both zeta and xi.

tau: also looked too narrow so I updated the 14 900 100 and 14 400 125. Please extrapolate again both tau.

upsilon and psi: the contrast looked a bit weird in the extrapolated 14 900 100, so I reworked in both 14 900 100 and 14 400 125. Please extrapolate again both.

omega: it looked a bit thin, especially on the base so I updated the 14 900 100. Please extrapolate again omega.

Yellow:

**Comment by dberlow** [comment]
Redrawn and space Greek U&l.c. are in the sources:
opsz14 wght100 wdth 50
opsz14 wght100 wdth 125
opsz14 wght900 wdth 50
opsz14 wght900 wdth 125

Change was also made to U.C. "A", @ opsz14 wght900 wdth 125
and its derivatives, Delta, Lambda and diacritics.

**Comment by irenevl** [comment]
Thanks @dberlow and @sannorozco for the update. I found some things that look suspicious so I'll have a more thorough look on the main masters.

## opsz14 wght100 wdth 50
- alpha: too squarish top right counter, maybe too dark the bottom outstroke
- beta: junction too thin 
- delta: leans forward
- zeta: a bump in the middle of the diagonal
- theta: too thin top left counter
- iota: spacing
- kappa: top diagonal too thin
- lambda: top instroke looks like a corner
- pi: left leg too monolinear
- upsilon: counter too close to the top
- chi: the left diagonal looks too monolinear
- psi: counter too close to the top
- omega: balance the countrast

## opsz14 wght100 wdth 125
- beta: junction too thin 
- delta: looks a bit unbalanced, a bit falling to the back
- epsilon: outside curve, especially top part, is bumpy
- zeta: a bump in the middle of the diagonal
- theta: too wide?
- lambda: top instroke looks like a corner
- xi: bottom counter pops to the left too much
- rho: too narrow?
- chi: the left diagonal looks too monolinear
- omega: beautiful :D

<img width="486" alt="Screenshot 2020-09-14 at 16 37 36" src="https://user-images.githubusercontent.com/11784297/93093032-e24f2e00-f6a8-11ea-954e-09eb61ba2aa7.png">

## opsz14 wght900 wdth 50
- alpha: too squarish top left side of the counter
- beta: junction too thin 
- delta: top stroke to short and too much to the left
- epsilon: junction has no contrast
- zeta: a bump in the middle of the diagonal, the terminal too squarish
- iota: spacing
- kappa: top diagonal too short
- nu : leans forward
- xi: toon arrow?  the terminal too squarish
- sigma: horizontal stroke too short
- upsilon: counter too close to the top
- chi: the left diagonal looks too monolinear
- psi: counter too close to the top
- finalsigma:  the terminal too squarish

## opsz14 wght900 wdth 125
- epsilon: outside curve, especially top part, is bumpy
- zeta: a bump in the middle of the diagonal, the terminal too squarish
- pi: left leg too monolinear
- rho: outside curve, especially top part, is bumpy
- sigma: horizontal stroke too short
- upsilon: bottom left of the counter too squarish
- chi: the left diagonal looks too monolinear
- psi: bottom left of the counter too squarish
- finalsigma:  the terminal too squarish

I need to check if home of the mistakes are coming from the "parent" masters, and I'll update them.

**Comment by irenevl** [comment]
20200927-28 Greek WIP commit:

update of Greek GF Core set, based on 12 August comments for:
- Amstelvar-Roman-opsz14-wght100-wdth50
- Amstelvar-Roman-opsz14-wght100-wdth125
- Amstelvar-Roman-opsz14-wght900-wdth50
- Amstelvar-Roman-opsz14-wght900-wdth125

also small rename of 
`tonoscmb` --> `tonoscomb` 
and 
`dieresistonoscmb` -->  `dieresistonoscomb` 
in all main and parametric masters.

**Comment by simoncozens** [comment]
I tried building Amstelvar today with my own toolchain (as a way to test it), and found that there are still naming issues with some of the glyphs, particularly `dieresiscomp` (should be `dieresiscomb`?), `dieresistonoscmb` (should be `dieresistonoscomb`?) and `tonoscmb` (should be `tonoscomb`?). Here is the full set of warnings that I got:

```
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz14-wght900-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz14-wght900-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz14-wght100-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz14-wght100-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght900-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght100-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght900-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresistonoscmb appears in Amstelvar-Roman-opsz8-wght900-wdth100.ufo but is not in default
# [warning] Incompatible glyph set: tonoscmb appears in Amstelvar-Roman-opsz8-wght900-wdth100.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght900-wdth100.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght100-wdth100.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght100-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght400-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresistonoscmb appears in Amstelvar-Roman-opsz8-wght400-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: tonoscmb appears in Amstelvar-Roman-opsz8-wght400-wdth50.ufo but is not in default
# [warning] Incompatible glyph set: dieresistonoscmb appears in Amstelvar-Roman-opsz8-wght400-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: tonoscmb appears in Amstelvar-Roman-opsz8-wght400-wdth125.ufo but is not in default
# [warning] Incompatible glyph set: dieresiscomp appears in Amstelvar-Roman-opsz8-wght400-wdth125.ufo but is not in default
```
