### ISSUE TITLE
Value system change for GRAD

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#209]
Per request, the GRAD axis values must be expressed in OS/2 wght values.

The default is to be 0, for no change from current design space location. 
new GRAD MIN = -300 
new GRAD max = 500

Please change source names, designspace file and generate new versions.

Calculation detailed below.

Amstelvar
XOPQ (H stem measure in 1/1000ths), 38,88,239
Os/2 100,400,900
GRAD’s XOPQ 36,88,141

Min total 50 /3, 17 XOPQ per os/2 100, 
Max total 151 /5, 30 XOPQ per Os/2 100.

New Amstelvar GRAD range
Min 50 = 300 os/2 units GRAD MIN = -300
Max 150 = 500 os/2 units GRAD MAX = 500

(see also github.com/TypeNetwork/Roboto-Flex/issues/129 for commented version of same process)

**Comment by sannorozco** [comment]
Updated Roman & Italic

**Comment by dberlow** [comment]
Thanks!

On Apr 7, 2021, at 8:09 PM, Santiago Orozco ***@***.***> wrote:

﻿
Updated Roman & Italic
