### ISSUE TITLE
ӑӓӝӧӱ composite order

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#216]
Composites Must have the base character first, and the accent(s) after, in all fonts since 1986.

Italic ӑӓӝӧӱ are incorrect and must be fixed by DB in all the masters of the design space.

All other Cy must now be manually checked by DB for composite order. 

Nothing can be build in Italic until it's been done.

**Comment by sannorozco** [comment]
This can be scripted, I can do it today.

**Comment by dberlow** [comment]
YOPQ will be correct... all others please proceed while I'm sleeping;)

**Comment by dberlow** [comment]
GRAD is also correct.

**Comment by sannorozco** [comment]
Done!
