### ISSUE TITLE
QA checks for letterform soundness

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Amstelvar#26]
Please check the "reasonable" ranges of sizes, widths, weights and grades (those used in "real world text typography") are good in Amstelvar :) 

From the very first version to the one currently available, Amstelvar already had the 3 currently registered axes, which are blended, "reigned in" so that the minimum width was by itself not resulting in anything too crazy, and probably the range that grade can travel can also be reduced to prevent a casual user from partying too hard.

**Comment by sberlow** [comment]
Does it make sense to set named instances for:
Micro,Text, Display, Banner
Grades for Micro and text (I assume)

Then restrict movement within the range of the named instances?
Then check outlines based on the restricted range?

**Comment by davelab6** [comment]
> Does it make sense to set named instances for: Micro-Text-Display-Banner, and Grades for Micro and text (I assume)

I think it may be nice for users of legacy systems to have access to such named instances. However, since this pilot project's purpose is to demonstrate "relative specification", it might be a bit of an own-goal to do so. 

> Then restrict movement within the range of the named instances?
>
> Then check outlines based on the restricted range?

Even without named instances, I this is what I'm suggesting: the range/subspace delineated by the 3 registered axes that are blended, plus (currently) unregistered grade axis, is smaller than the range/space created by the underlying 'parametric' axes. 

If users hit a "show all axes" button, they can then access this larger space, and they should be able to run around inside that space with scissors.

**Comment by sberlow** [comment]
Restrict movement
Check outlines

no named instances

**Comment by dberlow** [comment]
Leave us alone. This project is over and I'm gonna cancel the next one.

**Comment by sberlow** [comment]
My mistake, I added the Instances, it was a mistake.
the only part of this issue is to limit range

Restrict movement
Check outlines

no named instances

**Comment by dberlow** [comment]
"Then restrict movement within the range of the named instances"

I talked to Sam about this earlier this week and said "this is all we have to do", and I said "I don't want to do that, until after I finish this content we are contracted to provide in the mini site we are working on because that is the priority, and there may be working there that changes my mind about what limits we will set"

I'm sorry but that was not communicated to David Crossland but I am communicating it now.

I will get onto the final bit of this project after I finish the site. 

Clear?

**Comment by sberlow** [comment]
Agreed that the site comes first.
I was just tying to get these into Github
so we all knew what was needed...
