### ISSUE TITLE
Make new wdth and wght to MS Spec.?

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#27]
The spec for the two axes is here:
https://www.microsoft.com/typography/otspec/dvaraxisreg.html

That is weight a per OS/2 values, with the default at 400 and the rest of the axis spread out as best as possible. 

And a wdth with the default set to 100%,  I believe and the min and max calculated to % from the existing per mille values.

Dave C. has requested the original axes be renamed and kept, WDTH and WGHT are his suggestions, but I'm looking to add them to our Proposal/Registry with l.c. names.

**Comment by davelab6** [comment]
This is now done:

https://github.com/Microsoft/OpenTypeDesignVariationAxisTags/blob/master/Proposals/TypeNetwork_ParametricAxes/ProposalSummary_pwht.md 

https://github.com/Microsoft/OpenTypeDesignVariationAxisTags/blob/master/Proposals/TypeNetwork_ParametricAxes/ProposalSummary_pwth.md
