### ISSUE TITLE
Rewriting the AmstelvarAlpha Readme

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#32]
The Amstelvar Readme file was cobbled together from  an initial writing of it by me, notes from myself and others that were appended, and other edits along the way. It doesn't make enough sense, which may be why the TN axes proposal is not being as easily understood as it could be, and it does not make sense to attempt additional axes proposals, additional documentation of the Alpha, or ongoing documentation of whatever the next phase of Amstelvar development is, without stopping to fix the AmstelvarAlpha Readme now. 

So, There is a rewrite happening in google docs and a spreadsheet with attributes connected to what will be in the final alpha readme for going forward. Pleas let me tell you when these are ready for interaction, which they are not now. 

Thanks.

**Comment by dberlow** [comment]
This is an AmstelvarAlpha Issue, it's been resolved in email because the AmstelvarAlpha repository has gone missing, and I should be removed from _this_ Amstelvar repository!

**Comment by davelab6** [comment]
> There is a rewrite happening in google docs and a spreadsheet with attributes connected to what will be in the final alpha readme for going forward.

Where is this doc and sheet?

**Comment by davelab6** [comment]
I also have #36 open at the moment; it would be cool to include info about the final Alpha release in that README even though it is 'historical'

**Comment by sberlow** [comment]
https://github.com/TypeNetwork/Amstelvar/tree/amstelvar-alpha/documentation
marking closed
