### ISSUE TITLE
GOOGLE FONT AMTSTELVAR

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#34]
Alex,
Goggle fonts needs to test some variable fonts. We need two files:
1. an AmstelvarAlpha.ttf font with the default only.
2. an AmstelvarAlpha.ttf variable font with 
     the default and a wght axis only.
       a. recommended safe wght min = 156
       b. recommended safe wght max = 860
the file attached are visual presentation of these extremes and the regular fro reference.

Let me know, thanks.

![google wght test extremes](https://user-images.githubusercontent.com/1956494/35474828-b56c774a-0361-11e8-872a-66bbd196c5e7.png)
[Google WGHT test extremes.pdf](https://github.com/TypeNetwork/Amstelvar/files/1670368/Google.WGHT.test.extremes.pdf)

**Comment by dberlow** [comment]
This is an AmstelvarAlpha issue and should be removed from this repo.

**Comment by davelab6** [comment]
Alex emailed me the files so closing
