### ISSUE TITLE
Axes: Parametric Axes (ascii)

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/Amstelvar#39]
- [ ] XTRA
- [ ] YTRA
- [ ] XOPQ
- [ ] YOPQ

- [ ] YTLC
- [ ] YTUC

- [ ] YTAS
- [ ] YTDE

- [ ] YTFG
- [x] YTOS
- [x] YTUS
- [ ] YTAD
- [ ] YTDD
- [ ] XTAB
- [ ] YTSE

- [x] VUID
- [ ] VOTF

- [ ] YTCH
- [ ] XTCH
- [x] POPS
- [ ] PWTH
- [ ] PWHT

- [ ] UDLN

**Comment by sberlow** [comment]
@sberlow, define each axis

**Comment by dberlow** [comment]
I think we have defined the axis of this project, and this list goes beyond that list. 

I have started a sheet on this project and the axes above that have been checked, are not going to be on it. 

Thanks.

**Comment by sberlow** [comment]
Issue replaced by https://github.com/TypeNetwork/Amstelvar/issues/46
closing
