### ISSUE TITLE
Axes: Parametric (Latin Plus) Roman

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/Amstelvar#41]
- [x] XTRA
- [x] YTRA
- [x] XOPQ
- [x] YOPQ

- [x] YTLC
- [x] YTUC

- [x] YTAS
- [x] YTDE

- [x] YTFG
- [ ] YTOS
- [ ] YTUS
- [ ] YTAD
- [ ] YTDD
- [ ] XTAB
- [x] YTSE

- [ ] VOTF

- [ ] POPS
- [ ] PWTH
- [ ] PWHT

- [ ] UDLN

**Comment by davelab6** [comment]
Closing as related to Amstelvar Alpha
