### ISSUE TITLE
After All the italic glyphs are complete...

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#44]
...I can proceed with planning and paramtricizing axes.

Let me know, 

thanks.

**Comment by davelab6** [comment]
We should probably do a presentation & review & approval of the base italic glyph designs before proceeding with that :)

**Comment by dberlow** [comment]
This is correct. I am trying to get it so the entire glyph repertoire without a single one missing from either regular and italic de fault is presented for single review of the entire thing once, before we set out. 

Alex is almost done with the last of the italic, to complete that set completely, And the proofing of all glyphs possible in the glyph-proofing tool on the website.

**Comment by sberlow** [comment]
I am going to make issues for each of these tasks
Glyphs: Roman and Italic to Latin Plus (AS)
Review: Roman and Italic to Latin Plus (DB - DC)
Draw: Parametric Axes (DB - AS)

**Comment by sberlow** [comment]
Made individual issues for these tasks:
https://github.com/TypeNetwork/Amstelvar/issues/43
https://github.com/TypeNetwork/Amstelvar/issues/39
https://github.com/TypeNetwork/Amstelvar/issues/45

Closing
