### ISSUE TITLE
Axes: Parametric (Latin Plus) Italic

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/Amstelvar#46]
- [ ] XTRA
- [x] YTRA
- [x] XOPQ
- [ ] YOPQ

- [ ] YTLC
- [ ] YTUC

- [ ] YTAS
- [ ] YTDE

- [ ] YTFG
- [ ] YTOS
- [ ] YTUS
- [ ] YTAD
- [ ] YTDD
- [ ] XTAB
- [ ] YTSE

- [ ] VOTF

- [ ] POPS
- [ ] PWTH
- [ ] PWHT

- [ ] UDLN

**Comment by dberlow** [comment]
There are not YTOS, YTUS, VUID, YTCH, XTCH or POPS axes planned for this variable font.

**Comment by dberlow** [comment]
There is no XTAB axis planned for this font.

**Comment by davelab6** [comment]
I thought XTAB was used for the OpenType 'tnum' feature figures?

**Comment by dberlow** [comment]
X tab was Intended to vary the width of the instances of a tabular or monospaced style.

**Comment by davelab6** [comment]
And tabular numbers are not a tabular style? :)

**Comment by dberlow** [comment]
I count tnum as a feature to be stored either as a separate glyph, or as an instance along the votf axis.

**Comment by davelab6** [comment]
Closing as related to Amstelvar Alpha
