### ISSUE TITLE
Added superior figures, fractions and ordinals

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#48]
Alex is integrating to post.

**Comment by dberlow** [comment]
Alex, please also add the Chinese to both the fonts,  and Sam, to the glyph list?

**Comment by sberlow** [comment]
@davelab6 you nixed the Chinese correct?
If so let's close this issue

**Comment by davelab6** [comment]
If superior figures, fractions and ordinals are added, then sure

**Comment by davelab6** [comment]
Yes, lets leave the Chinese as it is in Amstelvar Alpha.

If superior figures, fractions and ordinals are added, please close
