### ISSUE TITLE
qa — vertical metrics font wide

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#49]
These vertical metrics in the general font info are mismatched between the Roman vs. the others

**Roman.ufo**
Currently
UPM = 2000
Ascender = 1500  (H @ 1500, O overshoot at 1520)
Descender = -500

**Italic.ufo**
UPM 2000
Asc = 1568
Desc =  -448

**Amstelvar-opszmax.ufo**
UPM 2000
Asc = 1568
Desc =  -448

**Amstelvar-ital-opszmax.ufo**
UPM 2000
Asc = 1568
Desc =  -448
_x-height value differs from Roman opszmax_

**Comment by dberlow** [comment]
These are all correct. Alignments and overshoots change a lot in valuable space.

**Comment by pichotta** [comment]
I understand and recall the 2000 UPM.  I have yet to understand the difference between the Roman Asc being 1500, and the Italic Asc being 1568, if the CapHt is the same?  Perhaps these values are not consequential in generated files. The values will remain 'as is' unless otherwise noted. Thank you

**Comment by dberlow** [comment]
The extender variety, in this particular family, is due to differences in sapes of the sheriffs. It is intentional.

**Comment by pichotta** [comment]
Ok. I understand that the asc and desc in the actual _outline_ data will change height depending on the style. 

To clarify I was referring to the numerical vert metrics values in the general font info fields.   I wasn't sure if the _fields_ in the font info would impact something like baseline shift across the family?

Ascender 1500 vs. 1568
Descender -500 vs. -448


<img width="1132" alt="general font info vert metrics" src="https://user-images.githubusercontent.com/6576107/37209587-c8a8e302-2373-11e8-83d5-b14d9f7ef3d5.png">

<img width="638" alt="b outline ascender across four masters" src="https://user-images.githubusercontent.com/6576107/37209592-cd155768-2373-11e8-8ac7-bd17316ad223.png">

**Comment by davelab6** [comment]
Why is the UPM 2000?

**Comment by dberlow** [comment]
1,000 isn’t enough, 2048 doesn’t scale to 1000 well, and 2000 does it all?

**Comment by pichotta** [comment]
Sounds good!
