### ISSUE TITLE
qa — { }

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#51]
opszmax 
{} - vertical mismatch

**Comment by dberlow** [comment]
Do not change my vertical metrics, thanks.

**Comment by pichotta** [comment]
<img width="579" alt="bottom" src="https://user-images.githubusercontent.com/6576107/37209852-a300bdd6-2374-11e8-8869-929b4ebe927d.png">

<img width="327" alt="ital_opszmax" src="https://user-images.githubusercontent.com/6576107/37209874-b11205f6-2374-11e8-872a-abb91af59776.png">

**Comment by sberlow** [comment]
fixed
