### ISSUE TITLE
qa - Italics lc height

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#52]
verifying that in the Italic lowercase it is intentional that few characters that are shorter relative to the others. e.g. **g, q, x, z**

<img width="1654" alt="ital lc string" src="https://user-images.githubusercontent.com/6576107/37083178-c3e0765e-21bc-11e8-9b0b-936882fed766.png">

<img width="700" alt="ital lc x" src="https://user-images.githubusercontent.com/6576107/37083197-d3e334e2-21bc-11e8-88bf-f2bd386bca17.png">

**Comment by dberlow** [comment]
I will check
