### ISSUE TITLE
qa — italic figure width opszmax

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#53]
noting that the figures in the max optical size in the italics are wider than the roman by design.

<img width="1016" alt="italic figure width opszmax" src="https://user-images.githubusercontent.com/6576107/37083405-67c9d59e-21bd-11e8-8d0c-3d2f4de10775.png">

**Comment by dberlow** [comment]
The Italic is incorrect. 

We, (FB design) are seeking ideas on how to handle tabular figures across a mighty weight axis, where "mighty" means a wide range of weights. A wide range of figure weights cannot easily be shoehorned into a single tabular width, (what with 1 having 1/2 the number of stems of 0 to begin with). So, without either crushing the ultra's weight and 0,6,8,9 counters, or airing out the thin 1 with too much tabular space, the Regular Amstelvar figs. are in slower limbo than the rest.

The italic is in 2x limbo. 

The figures of the width axis, where every weight of each of those widths have to be tabular are in 3x limbo. Etc.;)

There are ideas.
1. limit the range of tubularity from light to extra bold and do your best from there. 
2. figure out mathematical limits and turn those into ranges of tabular widths.
3.make an **xtab** axis and advocate applications allow the user to pick any pair of weights of a size and width, and then invoking the tnum feature will get average tabular width for the two styles.
4. Switch user into a GRAD axis when they want a Tabular set of figures.

Ask around. Most foundries may have not yet considered what tabular figures means for variable design spaces that include size, mighty weight, width and italic axes?

**Comment by davelab6** [comment]
Sam assigned this to milestone v2, which makes sense to me because this is a refinement issue rather than the core design
