### ISSUE TITLE
Order of glyphs in font

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#59]
Alex and I came to agree that it's useful for a font family to share the same glyph order, as opposed to having to search around through each style. 

So, Amstelvar-Roman-3 has that glyph order, except i moved "colonsign" out of the punctuation and into the monetary. 

The italic seems to have taken up its own glyph order, which is not useful. 

Please make sure that the italic and all subsequent source fonts of Amstelvar retain the same glyph order. 

thanks. 
<img width="1468" alt="amstelvar glyph order" src="https://user-images.githubusercontent.com/1956494/38266335-7278dde8-3746-11e8-9008-a25ba5df1962.png">

**Comment by pichotta** [comment]
Yes, I understand and agree. The Italic-2 which was received had a different sort order which I mistakenly thought was to be the template for the Italic.

We will revert to the Sort as you have shown with the "colonsign" before "currency".  I propose using the attached text file as a Sort for all. It follows the default Roman but also considers placement for the ǅǅǆǇǇǉǊǊǌ;  the renamed and reconciled accents; and the new /f.altbegin /f.altend /f.altshortd /f.altshorta.

@dberlow  If you do not like this attached Sort we can revert entirely to the pre-existing default Roman which adds the mentioned glyphs at the end of the char set.

[Amstelvar DB Sort_180403.txt](https://github.com/TypeNetwork/Amstelvar/files/1873845/Amstelvar.DB.Sort_180403.txt)

**Comment by djrrb** [comment]
@pichotta would you like to add a sort order file to the scripts folder, so that we can have a canonical version that we can continue to refer to as the project progresses?

**Comment by pichotta** [comment]
yes @djrrb   waiting to hear David's preference

**Comment by sberlow** [comment]
@djrrb @pichotta this is done?

**Comment by davelab6** [comment]
@dberlow please open this issue page and close if this is totally resolve.

**Comment by dberlow** [comment]
Please revert entirely to the pre-existing default Roman which adds the mentioned glyphs at the end of the char set.

**Comment by davelab6** [comment]
If you want it done, you need to leave the issue open :)

**Comment by dberlow** [comment]
Oh? I thought the issue was my response, and I would think getting it done would be a separate issue?

**Comment by djrrb** [comment]
Hi all, I actually just left on vacation... @sberlow did you want to reassign?

**Comment by sberlow** [comment]
I'm on it

**Comment by pichotta** [comment]
This .txt file has the preferred sort order by @dberlow for the Roman as per April 4

[DB Roman Sort_180404.txt](https://github.com/TypeNetwork/Amstelvar/files/2091302/DB.Roman.Sort_180404.txt)
