### ISSUE TITLE
Composited glyphs with kerning pairs. 

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#72]
This is an issue with the glyphs:
    LJ, Lj, lj, NJ, Nj, DZcaron, Dzcaron, dzcaron ...in variation space.

For an traditional style, combining complete glyphs together Is best accomplished quite simply by glyph accretion. the first character is composed, the second character composed beside it, the total of the composite's glyphs and width is the new glyph. If however a kern pair Exists for a combination forming these glyphs, then a style with these glyphs should be Composed using the first glyph with the kerning value added or Subtracted from its width, before the second glyph is composed for the final glyph.

For variations, and at the very end, after glyph contours, glyph spacing, font kerning, axes (including I believe any axis blending or synthesis), and intermediates, are all defined, We will use a script that DJR develops that will: Composite the first glyph, composite the second, move the second glyph for any kerning, set the width of the new glyph to the right side bearing the last glyph. 

This will be done in the default, all masters and intermediates effecting these glyphs or their kerning. 

If we need any refinements, we'll discover them along the way.

**Comment by behdad** [comment]
Why not use GSUB?

**Comment by dberlow** [comment]
Hey Behdad, we may at some point use that here. 

What would you suggest we sub for what?

**Comment by dberlow** [comment]
GSUB will certainly work for some instances of some of these glyphs. 

<img width="238" alt="screen shot 2018-04-26 at 8 57 13 am" src="https://user-images.githubusercontent.com/1956494/39307111-f5b5741e-492f-11e8-895a-a037b693ebec.png">

LJ e.g. might be able to use gsub if it doesn't kern at the default wght and wdth, in the opsz min. But as OPSZ goes up, the J ends up at the baselined and the options to "make a glyph out of it" change. 

These are _glyphs_, so we have a design commandment that says we do what we can to make them look like a glyph. 

So, in general, GSUB works for these if the user's environment has pair kerning, and both glyphs are the same as the default throughout the design space. 

I'm not so sure about the latter for all these glyphs as lJ implies, yet. But I am sure about the kerning needing to be in the composition.

We habe a while to ponder as we survey the design space.

**Comment by djrrb** [comment]
Commit 574b3efdf3b61821ba7d658136db11137fd043d1 has a new build with slugs for these characters.

**Comment by tiroj** [comment]
> move the second glyph for any kerning

This presumes, I think, that the kerning between the masters interpolates linearly, yes? If it doesn't, then you won't be able to interpolate the precomposed digraph glyph and maintain correct relationship between the composites — where 'correct' means mirroring kerning — without some mechanism to capture the non-linear kerning steps. The easy mechanism is to always decompose the digraph glyph to a sequence of the individual letters, in the ccmp feature (and which some normalising layout engines may do at the character level in any case, using Unicode compatibility mappings), but this may produce unwanted behaviour in tracking scenarios, depending on how a language conventionally handles digraphs in that respect, e.g.:

R I J K S M U S E U M

instead of 

R IJ K S M U S E U M

**Comment by davelab6** [comment]
@djr what is the definition of "slug"? :)

**Comment by djr** [comment]
@davelab6 This is not the djr you are looking for

**Comment by dberlow** [comment]
John: “This presumes, I think, that the kerning between the masters interpolates linearly, yes?”

Yes. Between all masters, intermediates and defaults, the kerning is linear.

**Comment by dberlow** [comment]
A slug is when two or more non-ligated glyphs are combined to a single glyph.

**Comment by sberlow** [comment]
@dberlow can this issue be closed?

**Comment by davelab6** [comment]
Assigning to v1 as it seems this is already done (in 574b3ef by DJR) and we are still in the v1 phase :) And Sam just said on the call that these glyphs worked for him the other day when he looked at them. 

DB please open this issue page and hit the close button if you agree. 

(BTW, that commit message is `build with slugmaker and avar` - what is "slugmaker"?)

**Comment by davelab6** [comment]
Closing as related to Amstelvar Alpha
