### ISSUE TITLE
Xopq axes

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#73]
In progress.

**Comment by davelab6** [comment]
Don't we want to do a full review of `opsz` the axis before jumping into the primary axes, since if design changes are needed to opsz masters, that will create more work for you to rework primary axes?

**Comment by dberlow** [comment]
I released the basic ascii opsz a month ago,
worked on the accents for 3 weeks awaiting a review
we posted the font last week, after adding all the y trans too
and now I'm going off to do more work....

I have to get to a corner, right or wrong,
to figure out how to make the space safe.

opsz and all the x trans are done,

xopq min is 8 glyphs from complete
yopq min is to be done next

that gives his an important place, thin, high contrast of all sizes, to
corral,

...while whatever changes may occur are fully facilitated by our great
faculties with git hub.

I am already stopping twice a day for documentation issues of all kinds,

Do you want me to stop for no other reason other than I'm building too much
font and you're scared of revisions?

**Comment by sberlow** [comment]
https://github.com/TypeNetwork/Amstelvar/issues/82
