### ISSUE TITLE
Glyph Sharing vs file size

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#74]
Glyph Sharing vs Glyph Expansion

Executive Summary:

This is a questing essay about two classes of sharing in the defininition of the Amstelvar glyphs repertoire. 

The first class of sharing are glyphs that currently need to be defined, even though they share contour congruency with an existing glyph in the design space, like uppercase A and Small Cap A, or uppercase Won and Small Cap Won. 

The second class of sharing are glyphs within the repertoire that are expected to be shared by different glyph groups, like A+B=C, a+b=c and 1+2=3, where the + and = are used with both cases and figures. 

first issue: When Amstemvar has small caps defined, all the glyphs highlighted in red and yellow below will also need to have small cap glyphs defined, along with A-Z and 0-9. So, as things stand now all of those glyphs will be instantiated as seperate contours with their own gvars, hints and kerning. 

see "Amstelvar Glyphork?"
<img width="1081" alt="amstelvar glyphork" src="https://user-images.githubusercontent.com/1956494/39429442-eb6a15ec-4c58-11e8-834f-41e1b20c2032.png">

Contour congruency, however, exists within the design space already, where those small cap A and Won contours, are already there with gvars, hinting and kerning, elsewhere in the design space. 

see Amstelvar EI Small caps
<img width="1142" alt="amstelvar ei small caps" src="https://user-images.githubusercontent.com/1956494/39429502-0cdd6170-4c59-11e8-99de-dfd22a375c30.png">

second issue:, Glyph sharing between cases is a more entrenched and insidious issue. 
<img width="362" alt="plus puss" src="https://user-images.githubusercontent.com/1956494/39429516-14afe8c8-4c59-11e8-9c02-9d157b61d668.png">

The gist of these sharing issues, and I've spoke with Dave about it with regards to the accents over, under and stacked with upper small caps and lowercase, is that, (because we cannot reference (composites?) from the glyphs of the whole design space, (that are outside of the current instance), we are going to have to produce multiple versions of all the glyphs above, one math glyph e.g. for each y-transparency axis. In some instances these glyphs can be compostited from a master-per-instance to a different alignment. In other cases that’s not possible and a different glyph will be gsubbed. The bottom line is that adding all there required contours, composited, gsub, gvar, hinting, kerning and probably more, will have the effect of doubling the size of this variable font.

**Comment by davelab6** [comment]
Rephasing this, to be sure I got it right:

Then OpenType 1.8.3 spec requires all "references" to glyphs (aka "composites" or "components") to be of the current instance location in the design space. 

However, there are many situations where different glyphs could be references to a parent component glyph but at different locations in the design space.

That means that these glyphs must be duplicated in the GLYF table, which increases filesize needlessly. 

For the "Type Network Axis Proposal" this may mean many many duplicated glyphs, for each of the y-transparency axes. This duplication of contours, composites, gsub rules, gvar deltas, hinting, GPOS rules (kerning) and probably more aspects, will increase the file size of such variable fonts substantially. 

Here are a few situations where glyphs could be shared, to improve the filesize of variable fonts:

#### Var Glyph Sharing Opportunity 1

Different Unicode encoded glyphs that have "contour congruency", ie their point topology is the same. 

Example set 1:

* 0x20A9 ₩
* 0xFFE6 ￦

Example set 2:

* Greek capital letter alpha: Α
  * Unicode hexadecimal: 0x391
  * In block: Greek and Coptic
 
* Latin capital letter a: A
  * Unicode hexadecimal: 0x41
  * In block: Basic Latin
 
* Cyrillic capital letter a: А
  * Unicode hexadecimal: 0x410
  * In block: Cyrillic
 
* Cherokee letter go: Ꭺ
  * Unicode hexadecimal: 0x13aa
  * In block: Cherokee

* Canadian syllabics carrier ro: ᗋ
  * Unicode hexadecimal: 0x15cb
  * In block: Unified Canadian Aboriginal Syllabics

* Canadian syllabics carrier gho: ᗅ
  * Unicode hexadecimal: 0x15c5
  * In block: Unified Canadian Aboriginal Syllabics

* Modifier letter capital a: ᴬ
  * Unicode hexadecimal: 0x1d2c
  * In block: Phonetic Extensions

* Mathematical sans-serif capital a: 𝖠
  * Unicode hexadecimal: 0x1d5a0
  * In block: Mathematical Alphanumeric Symbols

#### Var Glyph Sharing Opportunity 2

Different unencoded glyphs, accessed via OpenType features, that have "contour congruency" with other glyphs, ie their point topology is the same. 

Example glyph names:

* `A` and `A.smcp`
* `one` and `one.osf` and `one.tf` and `one.tosf`

#### Var Glyph Sharing Opportunity 3

Unicode encoded glyphs that are expected to look in different contexts. 

Example: The `plus` and `equals` glyphs have different positions and shapes when they are used with uppercase, lowercase, and with 4 kinds of figures:

* A+B=C
* a+b=c
* 1+2=3 tabular lining
* 1+2=3 tabular old-style
* 1+2=3 proportional lining
* 1+2=3 proportional old-style

**Comment by dberlow** [comment]
Dave,

I should also point out on this glyph issue,

'For the "Type Network Axis Proposal" this may mean many many
duplicated glyphs, for each of the y-transparency axes.'

I think more to the point, For the Amstelvar and Roboto projects, this
may mean many duplicated glyphs, for each of the y-transparency axes.

And to the point of history, as opposed to the Type Network Axis
Proposal, which proposes to solve this with vars, all these Google
fonts:

Pacifico

Dancing Scrpt

Gamji Flower

Great Vibes*

Sacramento

Tangerine

Damion

Niconne*

Mr. Dafoe

Mr Bedford

and

Miss Fajardose

at the

Grand Hotel

Because the have small x-heights, have some problem or other
associated with this issue, in displaying A+B=C, a+b=c and 1+2=3, by
only having one set of math signs.

* if it could decide means, + and = are not aligned vertically to each other.

Also, I would not rush off to point this out until we've solved it
both ways and can give a savings figure, but that up to you.

Cheers,

David.

**Comment by davelab6** [comment]
> I would not rush off to point this out until we've solved it both ways and can give a savings figure, but that up to you

Sounds good, I'll wait :)

**Comment by davelab6** [comment]
> I would not rush off to point this out until we've solved it both ways

ETA for this? :)

**Comment by dberlow** [comment]
Yes. This week I plan on reporting on general Amstelvar progress, on the repo.

In that report l will include a list of axes for suggested demos. 

For the demo of magic figures, in the subclass of compression demos, we will be able to show the difference between two approaches to glyph access in a variable font. 

One way is to make one variable font with all the axes, and design space locations for default style figures of other heights, widths, and contrasts, with the design space locations being used to simulate those same design space locations being stored in a VOTF table, to define opentype features.

Then, we can also proceed d I r e c t ly from that data set, to make and populate another variable font that has all the glyphs required for the same features, but with the glyphs added to the font, and not using design space locations.

This will give an inverted look at compression, where the developer has to decide, as the spec stands, how many users are going to use all the figure sets in a font, or how to subset them if they add them all, or with our work-around, how to provide them all without actually adding any glyphs.

Let me know if that sounds good

**Comment by davelab6** [comment]
Sounds good to me!

**Comment by davelab6** [comment]
Sam and I discussed this just now and it seems the small number of 'sharable' glyphs in the contracted glyph set are already duplicated; the remaining aspect of this issue is small caps, which is in fact out of scope for the contracted glyph set

I would suggest that in the specimen/documentation pages for the project, it would be possible to make a `parametric-smallcaps.js` which given a `.parametric-smallcaps` CSS class will adjust the "y cap transparency" (etc) to blend what would be the result of toggling a OpenType `smcp` feature via instance locations, if the format was smart enough to allow for such 'synthetic feature axis' - which today it is not. (@paleydreier maybe you want to file an issue on the demos tracker because Sam said this would not be part of the current efforts.)

So I'm going to create a "next time" milestone, and assign this issue to that milestone, and we can park this for now...

**Comment by dberlow** [comment]
Paragraph 1 is not correct and the original intent of the issue has been forgotten. Small caps were used as an example, with prior knowledge of the contracted glyph repertoire.  Those  features were discussed only to give people a feeling of scope. a+b=c, etc. was used as an example instead. The implications of not wanting to address the issue of manipulatable alignments and shared glyphs is that I will:
Make a specimen of what votf might do, 

Chop off most of the range of the Roman y transparency bundle, it’s range is too dangerous for the glyph repertoire as it is.

Not bother with anything but lc. Y transparent xht , descent and ascent in italic.

and not try to explain anything new until project management can catch up to real time team-oriented resolution of design issues.;)

**Comment by dberlow** [comment]
Variable GIDs = glyph id + variable design space location.

**Comment by davelab6** [comment]
Closing as related to Amstelvar Alpha; maybe interesting to @jeremiehornus
