### ISSUE TITLE
Elipsis-maker

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#76]
Someone might be using a script that is building the ellipsis incorrectly?
"InCorrect Elipsis" enclosed.
<img width="579" alt="incorrect elipsis" src="https://user-images.githubusercontent.com/1956494/39780510-7d3b7006-52da-11e8-99df-39f49aa8ef9e.png">
All incoming masters from me will have ellipsis measures like "Correct Elipsis", enclosed.
<img width="658" alt="correct elipsis" src="https://user-images.githubusercontent.com/1956494/39780523-855dc82e-52da-11e8-9f2f-ea04aa48bf7b.png">

**Comment by sberlow** [comment]
@djrrb is this fixed?
can we close?

**Comment by djrrb** [comment]
If @dberlow has drawn ellipses in the sources that’s what should appear in the font. I see the correct ellipsis in the latest generated font, and will close the issue. Let me know if it reappears.
