### ISSUE TITLE
Amstelvar-Roman.ufo from "review docs"

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/Amstelvar#78]
@sberlow In 51060c6c679d25e948ac95fcfc6bf2a07f634bb9, you committed a `Amstelvar-Roman.ufo` along with the docs. Was this intentional?

It appears to be a duplicate of `Amstelvar-Roman-3.ufo` that DB and I have been using, so let me know if it’s safe to delete.

**Comment by sberlow** [comment]
Yes delete
-- 
Sam Berlow
General Manager
Font Bureau
151 Beach Road
Tisbury, Ma. 02568

508-693-2425

www.fontbureau.com
