### ISSUE TITLE
Build-in XTRA

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#80]
XTRA its ready to add to the Amstelvar variable font.

**Comment by djrrb** [comment]
@dberlow I set this up yesterday, so I was ready for you. :-) When you pull the latest, you will a new font in the `/fonts` folder. 

This build went smoothly...I modified the build script and designspace but no changes were made to the UFOs.

I’m closing this but feel free to reopen if there are issues.

**Comment by dberlow** [comment]
Thanks!

**Comment by sberlow** [comment]
Is width close by?
-- 
Sam Berlow
General Manager
Font Bureau
151 Beach Road
Tisbury, Ma. 02568

508-693-2425

www.fontbureau.com
