### ISSUE TITLE
Amstelvar progress report

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#81]
Amstelvar progress report

This includes a report on the Roman, and italic. 
(issue# are just place-hoilders for things we can discuss before assigning values to.)

Roman
A of the b parametric axes are roughly complete, With final rough completion scheduled for June 6. Rough, means All the glyphs that need to be completed, in order to judge how the rest of the glyphs need to be completed, are complete. Issue#100

This includes every character in every parametric access except; the accent glyphs themselves, while the combined accents with base glyphs have been optically centered and properly unitized, issue#101, the tabular lining figures issue#102, small caps, issue#103 and their attendant monetary, punctuation and etc. also need completion.

The opsz axis is also drawn, Which was necessarily done and in adVance to provide a scope for the parametric axes. This is glyph complete and awaiting comments, issue#104.

Starting June 6, a number of advances can be pursued:
1. With approval of the Roman x-transparency axes bundle, the same axes for italic can begin.issue#104
2. Blending Roman weight and width axes.issue#106-7
3. Finishing Roman accents. issue#108
4. Testing safe boundaries of parametric space for Roman opsz.issue#109-12
5. Defining parametric locations for OT features and demonstrating production and use simulating VOTF, and the same without VOTF.issue#113
6. Developing a preliminary STAT table, fvar and mvar.issue#114-116.

Italic
All parametric and blended axes, as well as the entire design space, are dependent on the final corresponding appearances of the parametric and blended axes, as well as the entire design space of the Roman.

In order to give the client a com-let’s look at opsz, the min and max 
of that has been drawn to provide completeness to the Roman opsz.

Some number of glyphs for the italic await Roman completion, e.g. © ° and etc. will be substituted and probably respaced. The only glyph substitution italic-to-roman will be “micro”, which the Roman awaits upon italic completion.

The development plan for the italic, is to create and test the masters as a separate variable font, and when it is complete including kerning, shift all the glyphs from standard Unicode ids to private Unicode values and add a massive gsub for the ital axes from those private Unicode to substitute for Roman occupants of the standard Unicodes.

**Comment by sberlow** [comment]
In our meeting today, i would like to parse this into a schedule: milestones and issues, including:
Draw, build and review stages.

**Comment by davelab6** [comment]
Thanks for this!

I am going to review David's above report and comment on each thing, and file the issues as suggested. 

Before that, I am 

(1) going over the whole issue tracker with Sam for the next 30 mins, to allocate all issues into milestones, close any that are done, and update those still open with (a) an assignee and (b) and a status update comment. 

and (2) going to review the `opsz max and min` PDFs that were [posted a few weeks ago](https://github.com/TypeNetwork/Amstelvar/tree/51060c6c679d25e948ac95fcfc6bf2a07f634bb9/docs/2018-05-05%20opsz%20max%20and%20min%20) that DB has been waiting for me to give feedback on.
