### ISSUE TITLE
Per mille values are not included in the build

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#85]
All the values on the parametric axes in the current build of the VF are wrong. 

This spread sheet 
https://docs.google.com/spreadsheets/d/1DgnZYL0PDEhF9hqlXrGWX5iEtNkEVq0rvCx9cun-Lzc/edit#gid=0

...is all I have to get the proper values from the designer  into the variable font. 

**Column D** contains the proper _default_ values for each parametric axis.

The font currently had the values of Column E, (the upm values) instead. 

The variation of each axis', in upm, is in Columns O (min)  and Q (max) and these need to be 1/2 ed from the 2000 upm to a 1000 per mill value and that is what is supposed to be in the VF.

Let me know if there are issues with this, I'm stopped until the font is to TN spec. ;)

**Comment by dberlow** [comment]
Petr, 

Here is a correct axis value list for the amstelvar design space . Please make a new font, thanks.

**Comment by dberlow** [comment]
Sorry, that was too early in the morning to remember to paste. 

  <axes>
        <axis default="12" minimum="8" maximum="144"  name="opsz" tag="opsz">
            <labelname xml:lang="en">Optical Size</labelname>
        </axis>
        
        <axis default=“86” minimum=“18” maximum=“287”  name="XOPQ" tag="XOPQ">
            <labelname xml:lang="en">x opaque</labelname>
        </axis>
        
        <axis default=“402” minimum=“57” maximum=“892” name="XTRA" tag="XTRA">
            <labelname xml:lang="en">x transparent</labelname>
        </axis>
        
        <axis default=“62” minimum=“8” maximum=“102” name="YOPQ" tag="YOPQ">
            <labelname xml:lang="en">y opaque</labelname>
        </axis>
        
        <axis default=“500” minimum=“420” maximum=“570”  name="YTLC" tag="YTLC">
            <labelname xml:lang="en">y transparent lowercase</labelname>
        </axis>
        
        <axis default=“750” minimum=“500” maximum=“1000”  name="YTUC" tag="YTUC">
            <labelname xml:lang="en">y transparent uppercase</labelname>
        </axis>
        
        <axis default=“750” minimum=“425” maximum=“1000”  name="YTFG" tag="YTFG">
            <labelname xml:lang="en">y transparent figure height</labelname>
        </axis>
        
        <axis default=“-240” minimum=“-138” maximum=“-500”  name="YTDE" tag="YTDE">
            <labelname xml:lang="en">y transparent lowercase descender</labelname>
        </axis>

        <axis default=“750” minimum=“500” maximum=“1000”  name="YTAS" tag="YTAS">
            <labelname xml:lang="en">y transparent lowercase ascender</labelname>
        </axis>
        
        <axis default=“18” minimum="0" maximum=“50”  name="YTSE" tag="YTSE">
            <labelname xml:lang="en">serif rise</labelname>
        </axis>

    </axes>

**Comment by sberlow** [comment]
No values for 
x transparent
y opaque

Should they be commented out?

Or use the following:
XTRA
57	402	892
YOPQ
8	62	102

**Comment by dberlow** [comment]
Your values look correct as my memory serves.

There is a bug in pasting normal unformatted text from text edit into github. I will get around to avoiding using it when I have a chance.

**Comment by sberlow** [comment]
@petrvanblokland 
Comparing the current build with DB current settings,
The only change is: 
XOPQ current default 62 
change to 86
