### ISSUE TITLE
Italic l.c. criticism

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#98]
Redrawn with new beginnings and ends. 

Screens of "New and "Old"  below, uploaded.

<img width="1494" alt="new" src="https://user-images.githubusercontent.com/1956494/45000775-bd8e2f00-af95-11e8-88d6-06274577d869.png">
<img width="1493" alt="old" src="https://user-images.githubusercontent.com/1956494/45000776-bd8e2f00-af95-11e8-98df-d54869125f4b.png">

**Comment by davelab6** [comment]
Quick work :) A few quick comments:

Even higher contrast is good! The z is now crackling. I like it much more.

Some lumpiness yet to be ironed out, eg in the o. 

Glad to see the t sobered up.

The slight crumpling at the base of the stems (such as in h) I think decelerate the stroke speed and are not working so well. 

An exception to my idea there is in the r; now the r stem is now more subdued... would you bring back the spring in its step?

Why is the k loop is not joining the stem?

The new tails are sharp, I like where they are going. 

However, the g tail is now a little anemic. 

The f tail is good. What if the tail of f was more like its neck, more symmetical?

The j and y tails may extend to the left a little too much. 

Would it be too much opacity to have the left stem of the y terminate flat at the bottom?

**Comment by dberlow** [comment]
Please review by Sept. 16, so I can complete Italic opsz min and Italic Default to match.

**Comment by dberlow** [comment]
Quick work :) anything more that gathers before the 16th will be great!

**Comment by davelab6** [comment]
A few more:

The s may not be leaning forwards enough; and perhaps needs a little less stroke weight in the thinnest part of the top. 

The j tittle may be too far right.

Perhaps the k loop not joining the stem is OK at opsz-max; similarly for the bar of the e jutting out. 

The new curl on the top of the x may work well on the bottom too, like the first draft.
